const CREATE_ACCOUNT = "CREATE_ACCOUNT";
const RETRIVE_ACCOUNT = "RETRIVE_ACCOUNT";
const RETRIVE_ACCOUNT_NAME_LIST = "RETRIVE_ACCOUNT_NAME_LIST";

export { CREATE_ACCOUNT, RETRIVE_ACCOUNT, RETRIVE_ACCOUNT_NAME_LIST };
